//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поля установлены. Начало маркировки.
        /// </summary>
        internal static string MaxigrafStageForm_btnStart_Click_GraphStart {
            get {
                return ResourceManager.GetString("MaxigrafStageForm_btnStart_Click_GraphStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало загрузки LE скрипта.
        /// </summary>
        internal static string MaxigrafStageForm_btnStart_Click_LeLoadStart {
            get {
                return ResourceManager.GetString("MaxigrafStageForm_btnStart_Click_LeLoadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружен LE скрипт. Начало установки полей.
        /// </summary>
        internal static string MaxigrafStageForm_btnStart_Click_ValueSettingStart {
            get {
                return ResourceManager.GetString("MaxigrafStageForm_btnStart_Click_ValueSettingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркировка остановлена.
        /// </summary>
        internal static string MaxigrafStageForm_ConnectionOnReadEventHandler_GraphStopped {
            get {
                return ResourceManager.GetString("MaxigrafStageForm_ConnectionOnReadEventHandler_GraphStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркировка завершена успешно.
        /// </summary>
        internal static string MaxigrafStageForm_ConnectionOnReadEventHandler_GraphSuccess {
            get {
                return ResourceManager.GetString("MaxigrafStageForm_ConnectionOnReadEventHandler_GraphSuccess", resourceCulture);
            }
        }
    }
}
